import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app_sidebar";
import { fonts } from "@/fonts";



export const metadata: Metadata = {
  title: "372Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const font = fonts();
  return (
    <html lang="pt-br">
      <body
        className={`${font.poppinsSans.className} antialiased`}
      >
        <SidebarProvider>
          <Header />
          <AppSidebar />
          <main className="mt-20">
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
